package com.shrey.mongo.learning.dal;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;

import com.shrey.mongo.learning.document.Employee;
import com.shrey.mongo.learning.util.JsonUtils;

import lombok.extern.slf4j.Slf4j;

import org.bson.Document;
import org.bson.types.ObjectId;

import java.util.function.Consumer;

@Slf4j
public class EmployeeDal {

    private final MongoClient mongoClient;
    private final MongoDatabase mongoDatabase;
    private final MongoCollection<Document> mongoCollection;

    public EmployeeDal(final String hostUri, final String databaseName, final String collection) {
        this.mongoClient = MongoClients.create(hostUri);
        this.mongoDatabase = mongoClient.getDatabase(databaseName);
        this.mongoCollection = mongoDatabase.getCollection(collection);
        this.listCollection();
    }

    private void listCollection() {
        log.info("=== List collection - start ===");
        this.mongoDatabase
                .listCollectionNames()
                .forEach((Consumer<String>) collection -> log.info(collection));
        log.info("=== List collection - end ===");
    }

    public void list() {
        log.info("=== List records - start ===");
        this.mongoCollection
                .find()
                .forEach((Consumer<Document>) record ->log.info(record.toJson()));
        log.info("=== List records - end ===");
    }

    public String create(final Employee employee) {
        log.info("=== Inserting record - start ===");
        try {
            // Create document by converting object to JSON
            Document employeeDocument = new Document(Document.parse(JsonUtils.serialize(employee)));

            // Insert record
            this.mongoCollection
                    .insertOne(employeeDocument);

            // Fetch unique id generated by mongo API
            return employeeDocument
                    .getObjectId("_id")
                    .toString();
        } catch (Exception e) {
            throw new RuntimeException("Unable to insert record into collection", e);
        } finally {
            log.info("=== Inserting record - end ===");
        }
    }

    public Employee fetchById(final String id) {
        log.info("=== Fetch record - start ===");
        try {
            Document document = this.mongoCollection
                    .find(Filters.eq("_id", new ObjectId(id)))
                    .first();

            if (document != null) {
                return JsonUtils.deserialize(document.toJson(), Employee.class);
            } else {
                throw new RuntimeException("document id -> " + id+ " does not exist");
            }
        } catch (Exception e) {
            throw new RuntimeException("Unable to find document for id -> " + id, e);
        } finally {
            log.info("=== Fetch record - end ===");
        }
    }
}